name: Push changes

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-push:
    runs-on: self-hosted
    steps:
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TARGET_DIR="/home/ubuntu/Jellyfin-Universal-Catalogue"
          git config --global --add safe.directory "$TARGET_DIR"
          cd "$TARGET_DIR" || exit 1
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push "$REPO_URL" HEAD:main
          fi