name: Push changes

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-push:
    runs-on: self-hosted
    steps:
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TARGET_DIR="/home/ubuntu/Jellyfin-Universal-Catalogue/plugins"
          git config --global --add safe.directory "$TARGET_DIR"
          cd "$TARGET_DIR" || exit 1
          if [ -d ".git/rebase-merge" ] || [ -d ".git/rebase-apply" ]; then
            git rebase --abort || true
          fi
          if [ -f ".git/MERGE_HEAD" ]; then
            git merge --abort || true
          fi
          git submodule update --init --recursive
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push "$REPO_URL" HEAD:main
          else
            echo "No staged changes to commit."
          fi